-- ============================================
-- INMOALIA — Seed: Categorías
-- ============================================
insert into categories (slug, name, description, image_url, sort_order) values
  ('jardin', 'Jardín', 'Muebles y accesorios para exteriores', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800', 1),
  ('mesas', 'Mesas', 'Mesas de comedor, jardín y auxiliares', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', 2),
  ('sillas', 'Sillas', 'Sillas de comedor, jardín y butacas', 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800', 3),
  ('iluminacion', 'Iluminación', 'Lámparas de pie, apliques y colgantes', 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800', 4),
  ('decoracion', 'Decoración', 'Espejos, cuadros, jarrones y más', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 5),
  ('textil', 'Textil', 'Cojines, alfombras y mantas', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', 6),
  ('muebles', 'Muebles', 'Sofás, estanterías y más', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', 7),
  ('outlet', 'Outlet', 'Las mejores ofertas', 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800', 8)
on conflict (slug) do nothing;

-- ============================================
-- INMOALIA — Seed: 30 Productos
-- ============================================

-- JARDÍN EXTERIOR (8 productos)
insert into products (slug, name, description, price, cost_price, images, category, subcategory, tags, sku, supplier_sku, supplier, stock, weight_kg, dimensions, material, color, is_active, is_featured, meta_title, meta_desc) values

('conjunto-ratan-sintetico-4-plazas', 'Conjunto de Ratán Sintético 4 Plazas con Mesa', 'Elegante conjunto de jardín fabricado en ratán sintético de alta resistencia, incluye sofá de 2 plazas, 2 sillones individuales y mesa de centro con tablero de vidrio templado. Resistente a la intemperie y a los rayos UV. Cojines incluidos en tejido impermeable color crema. Perfecto para terrazas y jardines de estilo mediterráneo.', 649.00, 890.00, ARRAY['https://images.unsplash.com/photo-1590002989516-ae85dc4eca79?w=800','https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'], 'jardin', 'Conjuntos exterior', ARRAY['ratan','exterior','conjunto','terraza','mediterraneo'], 'INM-JAR-001', 'DXL-RAT-4P-01', 'dropxl', 12, 45.0, '{"width": 220, "height": 80, "depth": 150}', 'Ratán sintético PE, estructura aluminio', 'Natural/Crema', true, true, 'Conjunto Ratán Sintético 4 Plazas | INMOALIA', 'Conjunto de jardín en ratán sintético 4 plazas con mesa de cristal. Resistente a la intemperie. Envío gratis.'),

('tumbona-aluminio-ajustable-blanca', 'Tumbona de Aluminio Ajustable Posiciones', 'Tumbona de alto rendimiento en aluminio lacado en blanco mate con tejido de PVC trenzado transpirable en color blanco roto. Estructura plegable para fácil almacenamiento. 7 posiciones de reclinado. Capacidad máxima 150 kg. Resistente a la sal marina, ideal para piscinas y jardines costeros.', 189.00, 250.00, ARRAY['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800','https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800'], 'jardin', 'Tumbonas', ARRAY['tumbona','aluminio','piscina','exterior','plegable'], 'INM-JAR-002', 'DXL-TUM-AL-W', 'dropxl', 28, 8.5, '{"width": 190, "height": 42, "depth": 65}', 'Aluminio lacado, PVC trenzado', 'Blanco mate', true, false, 'Tumbona Aluminio Ajustable | INMOALIA', 'Tumbona de aluminio con 7 posiciones. Ideal para jardín y piscina. Envío gratis en pedidos +99€.'),

('pergola-bioclimatica-3x4', 'Pérgola Bioclimática Aluminio 3×4m con Lamas Orientables', 'Pérgola bioclimática de última generación en aluminio anodizado antracita. Lamas orientables de 0° a 135° para controlar la luz y ventilación. Incluye canalón integrado para evacuación de agua. Compatible con accesorios: cortinas laterales, mosquiteras, calefactores. Resistente a vientos de hasta 100 km/h.', 1890.00, 2400.00, ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], 'jardin', 'Pérgolas', ARRAY['pergola','bioclimatica','aluminio','terraza','lamas'], 'INM-JAR-003', 'DXL-PER-BIO-34', 'dropxl', 5, 85.0, '{"width": 300, "height": 250, "depth": 400}', 'Aluminio anodizado', 'Antracita', true, true, 'Pérgola Bioclimática 3x4m | INMOALIA', 'Pérgola bioclimática de aluminio con lamas orientables 3x4m. Control total de luz y temperatura.'),

('barbacoa-carbon-ruedas-acero', 'Barbacoa de Carbón con Ruedas Acero Inoxidable', 'Barbacoa de carbón en acero inoxidable 304 de alta calidad. Tapa con termómetro incorporado. Parrilla regulable en altura. Bandeja recoge cenizas extraíble. Ruedas de goma para fácil desplazamiento. Incluye gancho y bandeja lateral. Superficie de cocción: 50×35 cm.', 249.00, 320.00, ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800','https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'], 'jardin', 'Barbacoas', ARRAY['barbacoa','carbon','acero','parrilla','exterior'], 'INM-JAR-004', 'DXL-BAR-AC-001', 'dropxl', 18, 22.0, '{"width": 120, "height": 100, "depth": 60}', 'Acero inoxidable 304', 'Plata/Negro', true, false, 'Barbacoa Carbón Acero Inoxidable | INMOALIA', 'Barbacoa de carbón en acero inoxidable con tapa y termómetro. Calidad premium.'),

('fuente-jardin-piedra-artificial', 'Fuente de Jardín en Piedra Artificial con Bomba', 'Elegante fuente de jardín con acabado piedra natural en terracota. Incluye bomba sumergible de 35W silenciosa y cable de 5m. Flujo de agua regulable. Resistente a heladas hasta -20°C. Fácil instalación sin obra. Perfecta para crear ambientes mediterráneos o rústicos en patios y jardines.', 329.00, 420.00, ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800','https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'], 'jardin', 'Fuentes', ARRAY['fuente','jardin','piedra','mediterraneo','decoracion exterior'], 'INM-JAR-005', 'DRP-FNT-PT-01', 'droppery', 9, 35.0, '{"width": 45, "height": 90, "depth": 45}', 'Poliresina acabado piedra', 'Terracota', true, false, 'Fuente Jardín Piedra Artificial | INMOALIA', 'Fuente de jardín estilo piedra natural con bomba incluida. Resistente a heladas.'),

('mesa-auxiliar-exterior-teca', 'Mesa Auxiliar Exterior en Madera de Teca', 'Mesa auxiliar de exterior en madera de teca de plantación sostenible certificada FSC. Tratamiento al aceite natural para máxima protección UV y humedad. Patas con niveladores ajustables para superficies irregulares. La madera de teca envejece graciosamente adquiriendo tonos plateados si no se mantiene, o mantiene su dorado cálido con aceite anual.', 199.00, 270.00, ARRAY['https://images.unsplash.com/photo-1558882224-dda166733046?w=800','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'], 'jardin', 'Mesas exterior', ARRAY['teca','mesa auxiliar','exterior','madera','sostenible','FSC'], 'INM-JAR-006', 'DRP-MES-TK-AUX', 'droppery', 14, 12.0, '{"width": 50, "height": 55, "depth": 50}', 'Madera de teca FSC', 'Teca natural', true, false, 'Mesa Auxiliar Teca Exterior | INMOALIA', 'Mesa auxiliar de teca sostenible para exterior. Resistente y duradera.'),

('columpio-jardin-madera-acacia', 'Columpio de Jardín en Madera de Acacia con Toldo', 'Columpio familiar de madera de acacia maciza con tratamiento protector. Toldo de tela Oxford 600D resistente al agua y UV incluido. Asientos con cojines lavables. Capacidad para 3 adultos (300 kg). Estructura autoportante, no requiere instalación en pared o árbol. Montaje sencillo con manual ilustrado.', 459.00, 580.00, ARRAY['https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=800','https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'], 'jardin', 'Columpio', ARRAY['columpio','jardin','acacia','madera','toldo','familia'], 'INM-JAR-007', 'DXL-COL-AC-01', 'dropxl', 7, 55.0, '{"width": 195, "height": 155, "depth": 130}', 'Madera de acacia', 'Natural/Beige', true, true, 'Columpio Jardín Acacia con Toldo | INMOALIA', 'Columpio de jardín familiar en acacia con toldo incluido. Capacidad 300 kg.'),

('set-cojines-exterior-impermeables', 'Set de Cojines Exterior Impermeables (4 unidades)', 'Pack de 4 cojines para exterior en tejido Olefin de alta resistencia, impermeable y anti-manchas. Relleno de fibra de poliéster Quick Dry que se seca en minutos. Resistente a la decoloración UV. Compatible con la mayoría de sillas y sofás de exterior. Color: verde salvia, disponible también en arena y antracita.', 89.00, 120.00, ARRAY['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'], 'jardin', 'Textil exterior', ARRAY['cojines','exterior','impermeable','olefin','terraza'], 'INM-JAR-008', 'DXL-COJ-EXT-4P', 'dropxl', 45, 2.5, '{"width": 45, "height": 10, "depth": 45}', 'Tejido Olefin, relleno fibra Quick Dry', 'Verde salvia', true, false, 'Cojines Exterior Impermeables Set 4 | INMOALIA', 'Pack 4 cojines de exterior impermeables y anti-UV. Tejido Olefin premium.'),

-- MESAS (5 productos)
('mesa-comedor-madera-roble-180', 'Mesa de Comedor Roble Macizo 180×90 cm', 'Mesa de comedor en roble macizo americano de tala controlada. Acabado aceite natural que realza las vetas de la madera. Patas en acero negro mate con sistema de nivelación. Diseño atemporal que combina con interiorismo nórdico, industrial y contemporáneo. Capacidad para 8 personas. Entrega en 7-10 días.', 899.00, 1200.00, ARRAY['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800','https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=800','https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800'], 'mesas', 'Mesas comedor', ARRAY['mesa comedor','roble','madera maciza','nordico','industrial'], 'INM-MES-001', 'DRP-MES-ROB-180', 'droppery', 8, 68.0, '{"width": 180, "height": 76, "depth": 90}', 'Roble macizo americano', 'Natural con patas negro mate', true, true, 'Mesa Comedor Roble Macizo 180cm | INMOALIA', 'Mesa de comedor en roble macizo 180×90 cm. Diseño nórdico con patas de acero negro.'),

('mesa-centro-marmol-blanco-oval', 'Mesa de Centro Mármol Blanco Carrara Oval', 'Sofisticada mesa de centro con tablero en mármol blanco Carrara genuino de 2 cm de grosor. Base en acero dorado cepillado. Formato oval que favorece la circulación en salones pequeños. El mármol es un material natural con variaciones únicas en cada pieza. Incluye guías de mantenimiento de mármol.', 549.00, 750.00, ARRAY['https://images.unsplash.com/photo-1601628828688-632f38a5a7d0?w=800','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], 'mesas', 'Mesas centro', ARRAY['marmol','carrara','mesa centro','lujo','dorado','oval'], 'INM-MES-002', 'DRP-MES-MAR-OV', 'droppery', 4, 28.0, '{"width": 110, "height": 40, "depth": 60}', 'Mármol Carrara natural, base acero', 'Blanco/Dorado', true, true, 'Mesa Centro Mármol Carrara Oval | INMOALIA', 'Mesa de centro ovalada en mármol Carrara con base dorada. Lujo atemporal.'),

('mesa-escritorio-nogal-metal', 'Mesa de Escritorio Nogal Natural con Estructura Metálica', 'Escritorio en nogal natural de 2 cm de grosor sobre estructura de acero negro. Diseño minimalista ideal para home office moderno. Pasa-cables integrado en la parte trasera. Patas regulables ±2 cm. Madera de nogal de plantaciones europeas. Disponible en 120, 140 y 160 cm de ancho.', 429.00, 560.00, ARRAY['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800','https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800'], 'mesas', 'Escritorios', ARRAY['escritorio','nogal','home office','minimalista','metal'], 'INM-MES-003', 'DRP-ESC-NOG-01', 'droppery', 11, 32.0, '{"width": 140, "height": 75, "depth": 70}', 'Nogal natural, estructura acero', 'Nogal/Negro', true, false, 'Mesa Escritorio Nogal con Metal | INMOALIA', 'Escritorio en nogal y acero negro para home office moderno.'),

('mesa-jardin-aluminio-ceramica-160', 'Mesa de Jardín Aluminio con Tablero de Cerámica 160cm', 'Mesa de exterior de alta gama con estructura de aluminio fundido negro y tablero de cerámica ultracompacta 12 mm imitación piedra. La cerámica es resistente a la intemperie, rayos UV, arañazos y manchas. Patas con niveladores. Apilable. Diseño moderno que se integra perfectamente en terrazas contemporáneas.', 699.00, 900.00, ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800','https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'], 'mesas', 'Mesas jardín', ARRAY['mesa jardin','ceramica','aluminio','exterior','moderno'], 'INM-MES-004', 'DXL-MES-CER-160', 'dropxl', 6, 42.0, '{"width": 160, "height": 74, "depth": 90}', 'Aluminio fundido, cerámica ultracompacta', 'Negro/Piedra gris', true, false, 'Mesa Jardín Aluminio Cerámica 160cm | INMOALIA', 'Mesa de jardín premium en aluminio y cerámica ultracompacta. Resistente y elegante.'),

('mesa-auxiliar-ratan-natural-redonda', 'Mesita Auxiliar Ratán Natural Redonda Ø55cm', 'Mesita auxiliar artesanal tejida a mano en ratán natural. Base y estructura en madera de mango maciza. Acabado barniz natural que protege y resalta el tejido. Ideal como mesa de noche o mesa de apoyo en salón. El ratán natural aporta calidez y textura a cualquier decoración.', 149.00, 210.00, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'], 'mesas', 'Mesas auxiliares', ARRAY['ratan natural','mesa auxiliar','artesanal','bohemio','mango'], 'INM-MES-005', 'DRP-MES-RAT-55', 'droppery', 22, 6.5, '{"width": 55, "height": 55, "depth": 55}', 'Ratán natural, madera de mango', 'Natural', true, false, 'Mesita Auxiliar Ratán Natural Redonda | INMOALIA', 'Mesita auxiliar de ratán natural tejida a mano. Estilo boho-chic.'),

-- SILLAS (5 productos)
('silla-comedor-terciopelo-verde', 'Silla de Comedor Tapizada en Terciopelo Verde Bosque', 'Silla de comedor de diseño con estructura de madera de haya maciza en acabado negro. Tapizado en terciopelo de alto gramaje 600 g/m² en verde bosque. Relleno de espuma HR30 de alta resiliencia para mayor durabilidad. Patas con protectores de fieltro. Certificada REACH para seguridad química. Pack de 2 unidades.', 289.00, 380.00, ARRAY['https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'], 'sillas', 'Sillas comedor', ARRAY['silla comedor','terciopelo','verde','tapizada','haya','pack 2'], 'INM-SIL-001', 'DRP-SIL-TER-VD', 'droppery', 24, 9.0, '{"width": 48, "height": 86, "depth": 55}', 'Haya maciza, terciopelo 600g/m²', 'Verde bosque', true, true, 'Silla Comedor Terciopelo Verde | INMOALIA', 'Silla de comedor tapizada en terciopelo verde bosque. Pack de 2 unidades.'),

('butaca-lectura-lino-mostaza', 'Butaca de Lectura en Lino Mostaza con Patas de Nogal', 'Butaca de lectura de líneas nórdicas con tapizado en lino natural color mostaza. Estructura interna de madera maciza. Relleno de espuma viscoelástica + fibra de dacron para máxima comodidad. Patas de nogal macizo torneadas. Reposabrazos anchos. El tejido de lino es duradero, transpirable y ecológico. Medidas generosas para mayor confort.', 449.00, 600.00, ARRAY['https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'], 'sillas', 'Butacas', ARRAY['butaca','lectura','lino','mostaza','nordico','nogal'], 'INM-SIL-002', 'DRP-BUT-LIN-MOS', 'droppery', 16, 18.0, '{"width": 78, "height": 85, "depth": 80}', 'Lino natural, nogal macizo', 'Mostaza/Nogal', true, true, 'Butaca Lectura Lino Mostaza | INMOALIA', 'Butaca de lectura en lino mostaza con patas de nogal. Nórdica y confortable.'),

('silla-bar-acero-negro-cuero', 'Taburete Alto de Bar Acero Negro y Cuero Sintético', 'Taburete de barra de estilo industrial en acero negro forjado con asiento tapizado en cuero sintético marrón vintage. Reposapiés integrado. Altura regulable de 60-80 cm mediante gas. Capacidad 120 kg. Compatible con encimeras y barras de desayuno estándar. Juego de 2 unidades.', 199.00, 280.00, ARRAY['https://images.unsplash.com/photo-1549497538-303791108f95?w=800','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'], 'sillas', 'Taburetes', ARRAY['taburete','bar','industrial','cuero','acero negro','ajustable'], 'INM-SIL-003', 'DXL-TAB-BAR-IND', 'dropxl', 30, 12.0, '{"width": 40, "height": 100, "depth": 40}', 'Acero forjado, cuero sintético', 'Negro/Marrón vintage', true, false, 'Taburete Bar Industrial Negro | INMOALIA', 'Taburete de bar industrial en acero y cuero. Altura regulable. Pack de 2.'),

('silla-jardin-apilable-resina', 'Silla de Jardín Apilable Resina de Polipropileno', 'Silla de jardín apilable en polipropileno reforzado con fibra de vidrio, resistente a UV, humedad y temperatura extremas. Diseño ergonómico con apoyo lumbar. Totalmente apilable para fácil almacenamiento (hasta 8 sillas). Lavable con agua y jabón. Disponible en blanco, gris y antracita. Pack de 4.', 129.00, 180.00, ARRAY['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800','https://images.unsplash.com/photo-1590002989516-ae85dc4eca79?w=800'], 'sillas', 'Sillas jardín', ARRAY['silla jardin','apilable','resina','exterior','pack 4'], 'INM-SIL-004', 'DXL-SIL-JAR-PP4', 'dropxl', 55, 4.8, '{"width": 56, "height": 85, "depth": 54}', 'Polipropileno reforzado con fibra vidrio', 'Blanco', true, false, 'Silla Jardín Apilable Resina Pack 4 | INMOALIA', 'Pack 4 sillas jardín apilables en resina resistente a UV. Prácticas y duraderas.'),

('sillon-exterior-mimbre-gris', 'Sillón Exterior Mimbre Sintético con Cojín', 'Sillón de exterior de diseño escandinavo en mimbre sintético PE de alta densidad. Estructura en aluminio powder coat gris grafito. Cojín de asiento y respaldo incluidos en tela Sunbrella anti-UV. El tejido Sunbrella es la referencia mundial para textiles de exterior: no destiñe, no desarrolla hongos y es totalmente lavable.', 279.00, 370.00, ARRAY['https://images.unsplash.com/photo-1590002989516-ae85dc4eca79?w=800','https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800'], 'sillas', 'Sillones exterior', ARRAY['sillon','exterior','mimbre','sunbrella','escandinavo','gris'], 'INM-SIL-005', 'DRP-SIL-MIM-GR', 'droppery', 13, 14.0, '{"width": 70, "height": 80, "depth": 72}', 'Mimbre PE, aluminio, Sunbrella', 'Gris grafito', true, false, 'Sillón Exterior Mimbre Gris | INMOALIA', 'Sillón de jardín en mimbre sintético con cojín Sunbrella. Diseño escandinavo.'),

-- ILUMINACIÓN (5 productos)
('lampara-pie-arco-marmol-negro', 'Lámpara de Pie Arco con Base de Mármol Negro', 'Lámpara de pie de diseño con arco en acero negro mate y base en mármol negro Marquina pulido. Pantalla en lino natural Ø40 cm. Altura total 190 cm. Casquillo E27. Compatible con bombillas LED hasta 60W. Cable de tela negro trenzado 2m. La base de mármol aporta la estabilidad necesaria para el arco.', 399.00, 520.00, ARRAY['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'], 'iluminacion', 'Lámparas pie', ARRAY['lampara pie','arco','marmol','lino','negro','design'], 'INM-ILU-001', 'DRP-LMP-ARC-MRB', 'droppery', 11, 9.0, '{"width": 190, "height": 190, "depth": 50}', 'Acero, mármol Marquina, lino', 'Negro/Natural', true, true, 'Lámpara Pie Arco Mármol Negro | INMOALIA', 'Lámpara de pie arco con base de mármol negro Marquina y pantalla de lino.'),

('aplique-pared-ratan-natural', 'Aplique de Pared Ratán Natural Artesanal', 'Aplique de pared artesanal tejido a mano en ratán natural por artesanos de Bali. Pantalla semiesférica Ø30 cm. Casquillo E14 incluido. Emite una luz cálida y tamizada que crea ambientes acogedores. Cada pieza es única y puede presentar ligeras variaciones. Certificado CE. Cable oculto, requiere conexión a electricista.', 89.00, 130.00, ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800','https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800'], 'iluminacion', 'Apliques', ARRAY['aplique','ratan','artesanal','bali','boho','pared'], 'INM-ILU-002', 'DRP-APL-RAT-30', 'droppery', 32, 0.9, '{"width": 30, "height": 20, "depth": 15}', 'Ratán natural', 'Natural', true, false, 'Aplique Pared Ratán Natural Artesanal | INMOALIA', 'Aplique de pared en ratán tejido a mano. Luz cálida y acogedora estilo boho.'),

('lampara-colgante-ceramica-verde', 'Lámpara Colgante de Cerámica Verde Botella', 'Lámpara colgante artesanal en cerámica esmaltada verde botella con reflejos irisados. Fabricada a mano en Portugal por ceramistas especializados. Cable textil trenzado verde 1.5m regulable. Casquillo E27. Compatible con bombilla Edison vintage Ø95 mm. Ideal para cocinas, comedores y rincones de lectura. Certificado CE/RoHS.', 149.00, 200.00, ARRAY['https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800','https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800'], 'iluminacion', 'Lámparas colgantes', ARRAY['lampara colgante','ceramica','verde','artesanal','portugal','diseño'], 'INM-ILU-003', 'DRP-LMP-CER-VD', 'droppery', 18, 2.5, '{"width": 18, "height": 22, "depth": 18}', 'Cerámica esmaltada', 'Verde botella', true, true, 'Lámpara Colgante Cerámica Verde | INMOALIA', 'Lámpara colgante artesanal en cerámica verde botella. Fabricada en Portugal.'),

('lampara-sobremesa-travertino', 'Lámpara de Sobremesa en Travertino Natural', 'Lámpara de sobremesa de lujo con base en travertino romano natural mecanizado. Cada pieza presenta vetas y tonos únicos. Pantalla de lino natural Ø25 cm. Altura total 45 cm. Casquillo E14. Diseño minimalista de influencia italiana. Incluye bombilla LED regulable 6W 2700K.', 229.00, 310.00, ARRAY['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800','https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800'], 'iluminacion', 'Lámparas sobremesa', ARRAY['lampara sobremesa','travertino','marmol','lujo','italiano','lino'], 'INM-ILU-004', 'DRP-LMP-TRA-01', 'droppery', 9, 3.5, '{"width": 25, "height": 45, "depth": 25}', 'Travertino natural, lino', 'Travertino/Natural', true, true, 'Lámpara Sobremesa Travertino | INMOALIA', 'Lámpara de sobremesa con base de travertino natural. Diseño italiano minimalista.'),

('tira-led-exterior-ip65-5m', 'Tira LED Exterior IP65 5m Luz Cálida + Controlador', 'Tira LED de exterior con protección IP65 contra polvo y lluvia. 5 metros de longitud con 300 LEDs SMD 2835 de alta eficiencia. Luz cálida 3000K. Consumo: 24W. Incluye controlador bluetooth para ajustar intensidad y color desde app. Autoadhesiva. Compatible con sistema de automatización del hogar. Garantía 3 años.', 69.00, 95.00, ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800','https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800'], 'iluminacion', 'LED', ARRAY['tira led','exterior','ip65','smart','bluetooth','calida'], 'INM-ILU-005', 'DXL-LED-EXT-5M', 'dropxl', 67, 0.6, '{"width": 500, "height": 1, "depth": 1}', 'PCB aluminio, LEDs SMD 2835', 'Blanco cálido 3000K', true, false, 'Tira LED Exterior IP65 5m | INMOALIA', 'Tira LED exterior 5m con control bluetooth. IP65, luz cálida 3000K.'),

-- DECORACIÓN (5 productos)
('espejo-redondo-marco-ratan-80', 'Espejo Redondo con Marco de Ratán Natural Ø80cm', 'Espejo de pared circular con marco trenzado a mano en ratán natural. Cristal de 5mm con tratamiento antidistorsión. Ø80 cm. Colgador incluido. El ratán natural envejece con gracia aportando carácter. Ideal para recibidores, dormitorios y salones de estilo étnico, boho o natural. Certificado espejo de seguridad.', 179.00, 250.00, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800','https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800'], 'decoracion', 'Espejos', ARRAY['espejo','redondo','ratan','boho','etnico','pared'], 'INM-DEC-001', 'DRP-ESP-RAT-80', 'droppery', 19, 5.5, '{"width": 80, "height": 80, "depth": 5}', 'Ratán natural, cristal 5mm', 'Natural', true, true, 'Espejo Redondo Ratán Natural Ø80cm | INMOALIA', 'Espejo de pared circular con marco de ratán tejido a mano. Ø80 cm boho-chic.'),

('jarrón-ceramica-artesanal-barro', 'Jarrón de Cerámica Artesanal en Barro Refractario', 'Jarrón decorativo artesanal en barro refractario torneado a mano y cocido en horno de leña. Acabado en óxido de hierro que crea tonos únicos entre el negro y el marrón oscuro con reflejos metálicos. Cada pieza es única. Apto para flores secas y artificiales. 3 tamaños disponibles: S (20cm), M (35cm), L (50cm).', 95.00, 140.00, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], 'decoracion', 'Jarrones', ARRAY['jarron','ceramica','artesanal','barro','wabi-sabi','decoracion'], 'INM-DEC-002', 'DRP-JAR-CER-M', 'droppery', 25, 3.2, '{"width": 18, "height": 35, "depth": 18}', 'Barro refractario', 'Negro/Marrón oscuro', true, false, 'Jarrón Cerámica Artesanal Barro | INMOALIA', 'Jarrón artesanal en barro cocido a leña. Estética wabi-sabi única.'),

('cuadro-abstracto-canvas-100x80', 'Cuadro Abstracto en Canvas Premium 100×80cm', 'Obra de arte abstracto contemporáneo impresa en canvas de algodón 100% de 380g/m² mediante tecnología giclée. Colores que no destiñen con el tiempo. Bastidor de madera de pino 4 cm de profundidad. Listo para colgar. Serie limitada de 100 ejemplares numerados. Estilo paleta terrosa y verde salvia, perfecto para interiores mediterráneos y nórdicos.', 189.00, 260.00, ARRAY['https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800','https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800'], 'decoracion', 'Cuadros', ARRAY['cuadro','abstracto','canvas','arte','giclée','mediterraneo'], 'INM-DEC-003', 'DRP-CUA-ABS-100', 'droppery', 8, 2.0, '{"width": 100, "height": 80, "depth": 4}', 'Canvas algodón 380g, bastidor pino', 'Palette neutra/verde salvia', true, false, 'Cuadro Abstracto Canvas 100×80cm | INMOALIA', 'Cuadro abstracto en canvas premium 100×80 cm. Impresión giclée, edición limitada.'),

('macetero-xl-terracota-estilo-griego', 'Macetero XL de Terracota Estilo Greco Romano Ø50cm', 'Macetero de gran formato en terracota prensada con relieves de inspiración greco-romana. Ø50 cm, altura 60 cm. Agujero de drenaje con rejilla incluida. Resistente a heladas hasta -10°C. Ideal para plantas de gran porte: olivos, agaves, bambú, lavandas. Peso sin tierra: 18 kg. Aporta personalidad monumental a terrazas y jardines.', 129.00, 180.00, ARRAY['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], 'decoracion', 'Maceteros', ARRAY['macetero','terracota','xl','greco romano','jardin','terraza'], 'INM-DEC-004', 'DXL-MAC-TER-XL', 'dropxl', 14, 18.0, '{"width": 50, "height": 60, "depth": 50}', 'Terracota prensada', 'Terracota', true, false, 'Macetero XL Terracota Greco Romano | INMOALIA', 'Macetero XL terracota con relieves greco-romanos. Ø50 cm, resistente a heladas.'),

('bandeja-decorativa-mango-dorada', 'Bandeja Decorativa en Madera de Mango con Asas Doradas', 'Bandeja decorativa multifunción en madera de mango maciza acabada en blanco roto con asas de latón dorado. Dimensiones: 50×30×8 cm. Perfecta para organizar el salón, como centro de mesa o en baños. La madera de mango es una madera tropical sostenible de alta densidad y hermosas vetas. Pieza versátil y atemporal.', 69.00, 95.00, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'], 'decoracion', 'Decoración mesa', ARRAY['bandeja','mango','dorado','decoracion','salon','versatil'], 'INM-DEC-005', 'DRP-BAN-MAN-GD', 'droppery', 38, 1.8, '{"width": 50, "height": 8, "depth": 30}', 'Madera de mango, latón', 'Blanco roto/Dorado', true, false, 'Bandeja Decorativa Mango Dorada | INMOALIA', 'Bandeja decorativa de mango y asas doradas. Versátil para salón, mesa o baño.'),

-- TEXTIL HOGAR (4 productos)
('alfombra-kilim-lana-250x350', 'Alfombra Kilim Artesanal Lana 250×350cm', 'Alfombra de lana natural artesanal con diseño kilim de inspiración turca. Tejida a mano por artesanas bereber en telar tradicional. Lana de oveja cardada y teñida con tintes naturales. Reverso en yute natural. Certificada Oeko-Tex Standard 100. Instrucciones de lavado: aspirar semanalmente, limpiar manchas en seco. Única en su diseño.', 449.00, 620.00, ARRAY['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'], 'textil', 'Alfombras', ARRAY['alfombra','kilim','lana','artesanal','bereber','boho'], 'INM-TEX-001', 'DRP-ALF-KIL-350', 'droppery', 6, 8.5, '{"width": 250, "height": 1, "depth": 350}', 'Lana natural, reverso yute', 'Multicolor terracota/beige', true, true, 'Alfombra Kilim Artesanal Lana 250×350 | INMOALIA', 'Alfombra kilim artesanal en lana natural 250×350 cm. Tejida a mano, Oeko-Tex.'),

('manta-alpaca-natural-140x200', 'Manta de Alpaca Natural 140×200cm', 'Manta de lujo en mezcla de alpaca 50% y merino 50%. Suavidad excepcional: la fibra de alpaca es hipoalergénica, más suave que el cashmere y con mayor capacidad térmica. Gramaje 400g/m². Acabados franjados a mano. Certificado GRS (Global Recycled Standard). Perfecta para sofás, dormitorios y como accesorio de estilo.', 189.00, 260.00, ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'], 'textil', 'Mantas', ARRAY['manta','alpaca','merino','lujo','hipoalergenica','nordica'], 'INM-TEX-002', 'DRP-MAN-ALP-140', 'droppery', 21, 0.8, '{"width": 140, "height": 1, "depth": 200}', 'Alpaca 50%, Merino 50%', 'Beige natural', true, true, 'Manta Alpaca Natural 140×200cm | INMOALIA', 'Manta de alpaca y merino 140×200 cm. Certificada GRS, hipoalergénica y lujosa.'),

('set-cojines-lino-natural-45x45', 'Set de Cojines de Lino Natural 45×45cm (Pack 2)', 'Set de 2 cojines en lino natural sin blanquear de máxima calidad. Funda con cierre de cremallera oculta. Relleno de fibra de poliéster siliconado 700g para forma perfecta. El lino es la fibra más ecológica: crece sin pesticidas, consume poca agua y es biodegradable. Lavable a 30°C. Certificado Oeko-Tex. Disponible en 4 colores: natural, sage, blush y antracita.', 59.00, 80.00, ARRAY['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'], 'textil', 'Cojines', ARRAY['cojines','lino','natural','pack 2','ecologico','lavable'], 'INM-TEX-003', 'DRP-COJ-LIN-45-2', 'droppery', 48, 1.4, '{"width": 45, "height": 15, "depth": 45}', 'Lino natural, fibra siliconada', 'Lino natural', true, false, 'Cojines Lino Natural 45×45 Pack 2 | INMOALIA', 'Pack 2 cojines de lino natural 45×45 cm. Ecológicos, Oeko-Tex, lavables.'),

('cortina-lino-lavado-250x140', 'Cortina de Lino Lavado 250×140cm', 'Cortina de lino pre-lavado de 250g/m² con acabado ligeramente arrugado que es parte de su estética natural. Ojales metálicos inoxidables para barra Ø19-25 mm. Efecto light-filtering: filtra la luz sin oscurecer. Tratamiento anti-manchas. Lavable a 30°C. Venta por unidad. El lino lavado crea cortinas con mucho movimiento y elegancia casual mediterránea.', 89.00, 120.00, ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'], 'textil', 'Cortinas', ARRAY['cortina','lino','lavado','mediterraneo','light-filtering','ojales'], 'INM-TEX-004', 'DRP-COR-LIN-250', 'droppery', 33, 1.2, '{"width": 140, "height": 250, "depth": 1}', 'Lino pre-lavado 250g/m²', 'Lino natural/Blanco roto', true, false, 'Cortina Lino Lavado 250×140cm | INMOALIA', 'Cortina de lino lavado 250×140 cm con ojales. Elegancia mediterránea casual.')

on conflict (slug) do nothing;
