-- Sofá VENETTO 2 plazas (operativas-sniper / catálogo fabricante SDM; referencia 290.SVENE2SNE).
-- PVP tienda 425 € · coste proveedor 345 €.
-- Fotos desde ficha pública gruposdm.com (mismo modelo); next.config debe permitir hostname gruposdm.com.

insert into products (
  slug,
  name,
  description,
  price,
  cost_price,
  images,
  category,
  subcategory,
  tags,
  sku,
  supplier_sku,
  supplier,
  stock,
  weight_kg,
  dimensions,
  material,
  color,
  is_active,
  is_featured,
  meta_title,
  meta_desc,
  supplier_product_url
) values (
  'sofa-venetto-2-plazas-acero-inoxidable-similpiel-negra',
  'Sofá VENETTO, 2 plazas · acero inoxidable · similpiel negra',
  'Sofá de diseño, 2 plazas. Estructura tubular de acero inoxidable. Interior de espuma de gran densidad. Tapizado en similpiel negra; otros acabados bajo pedido. Disponible sofá de 3 plazas a juego en catálogo. Dimensiones (cm): ancho 132, fondo 70, alto 69. Embalaje: plástico y cartón. Unidades: 1; volumen: 0,666 m³. Producto nuevo con certificado (test report) de laboratorio internacional homologado (normativa UNE o equivalente internacional). Referencia proveedor 290.SVENE2SNE.',
  425.00,
  345.00,
  array[
    'https://gruposdm.com/38580-thickbox_default/venetto-sofa-2-seater-stainless-steel-black-synthetic-leather.jpg',
    'https://gruposdm.com/38581-thickbox_default/venetto-sofa-2-seater-stainless-steel-black-synthetic-leather.jpg'
  ]::text[],
  'muebles',
  'Sofás y butacas',
  array['venetto','sofá','salón','similpiel','acero inoxidable','diseño','muebles'],
  'INM-SVENE2SNE',
  '290.SVENE2SNE',
  'operativas-sniper',
  5,
  null,
  '{"width": 132, "height": 69, "depth": 70}'::jsonb,
  'Acero inoxidable, espuma alta densidad, similpiel',
  'Negro',
  true,
  true,
  'Sofá VENETTO 2 plazas acero inoxidable similpiel negra | INMOALIA',
  'Sofá de diseño VENETTO: estructura acero inoxidable, similpiel negra, 132×70×69 cm. Certificación UNE. Referencia 290.SVENE2SNE.',
  'https://gruposdm.com/es/sofas-butacas-y-sillones/sofas-y-sillones/sofa-de-2-plazas/sofa-venetto-2-plazas-acero-inoxidable-similpiel-negra.html'
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  cost_price = excluded.cost_price,
  images = excluded.images,
  category = excluded.category,
  subcategory = excluded.subcategory,
  tags = excluded.tags,
  sku = excluded.sku,
  supplier_sku = excluded.supplier_sku,
  supplier = excluded.supplier,
  stock = excluded.stock,
  weight_kg = excluded.weight_kg,
  dimensions = excluded.dimensions,
  material = excluded.material,
  color = excluded.color,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  meta_title = excluded.meta_title,
  meta_desc = excluded.meta_desc,
  supplier_product_url = coalesce(products.supplier_product_url, excluded.supplier_product_url),
  updated_at = now();
