-- Sillón oficina VERTON blanco / malla y asiento verde (Grupo SDM · ref. 766.SVEABMAVE).
-- Coste proveedor 44,10 € · PVP tienda 89,10 € (45 € ganancia neta).

insert into products (
  slug,
  name,
  description,
  price,
  cost_price,
  images,
  category,
  subcategory,
  tags,
  sku,
  supplier_sku,
  supplier,
  stock,
  weight_kg,
  dimensions,
  material,
  color,
  is_active,
  is_featured,
  meta_title,
  meta_desc,
  supplier_product_url
) values (
  'sillon-oficina-verton-blanco-malla-y-asiento-verde',
  'Sillón de oficina VERTON, blanco · malla y asiento verde',
  'Sillón de oficina alto y moderno con cabezal. Regulación de altura mediante cilindro neumático. Mecanismo de basculación con mando de ajuste de la intensidad. Armazón de polipropileno reforzado con fibra de vidrio de color blanco. Base de nylon. Tapizado del respaldo en malla verde, cabezal en similpiel verde y asiento en tejido acrílico verde. Otros colores disponibles; bajo pedido se pueden suministrar otros acabados.

Dimensiones (cm): ancho 60, fondo 62, alto 106–116. Embalaje: plástico y cartón. Unidad: 1 · volumen: 0,09 m³. Producto nuevo con certificado (test report) emitido por laboratorio internacional homologado, con detalle del cumplimiento de la norma UNE o su equivalente internacional.',
  89.10,
  44.10,
  array[
    '/imagenes/productos/sillon-oficina-verton-blanco-malla-y-asiento-verde-1.jpg',
    '/imagenes/productos/sillon-oficina-verton-blanco-malla-y-asiento-verde-2.jpg',
    '/imagenes/productos/sillon-oficina-verton-blanco-malla-y-asiento-verde-3.jpg',
    '/imagenes/productos/sillon-oficina-verton-blanco-malla-y-asiento-verde-4.jpg'
  ]::text[],
  'sillas',
  'Sillas de oficina',
  array['oficina','sillón','dirección','malla','Verton','blanco','verde','basculante','ergonómico']::text[],
  'INM-SVEABMAVE',
  '766.SVEABMAVE',
  'gruposdm',
  18,
  null,
  '{"width": 60, "height": 116, "depth": 62}'::jsonb,
  'Polipropileno reforzado con fibra de vidrio, malla, similpiel, tejido acrílico',
  'Blanco y verde',
  true,
  false,
  'Sillón de oficina VERTON blanco malla y asiento verde | INMOALIA',
  'Sillón de dirección VERTON blanco con malla y asiento verde. Basculante, cabezal y 60×62×106–116 cm. Certificación UNE.',
  'https://gruposdm.com/es/oficinas/sillas-de-oficinas/sillones-de-direccion/sillon-de-oficina-verton-blanco-malla-y-asiento-verde.html'
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  cost_price = excluded.cost_price,
  images = excluded.images,
  category = excluded.category,
  subcategory = excluded.subcategory,
  tags = excluded.tags,
  sku = excluded.sku,
  supplier_sku = excluded.supplier_sku,
  supplier = excluded.supplier,
  stock = excluded.stock,
  weight_kg = excluded.weight_kg,
  dimensions = excluded.dimensions,
  material = excluded.material,
  color = excluded.color,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  meta_title = excluded.meta_title,
  meta_desc = excluded.meta_desc,
  supplier_product_url = coalesce(products.supplier_product_url, excluded.supplier_product_url),
  updated_at = now();
