-- Sillón oficina MAINZ similpiel gris (Grupo SDM · ref. 762.SMAINASGR).
-- PVP: coste 132 € + transporte 33 € + neto 60 € + IVA 21 % = 272,25 €.

insert into products (
  slug,
  name,
  description,
  price,
  cost_price,
  images,
  category,
  subcategory,
  tags,
  sku,
  supplier_sku,
  supplier,
  stock,
  dimensions,
  material,
  color,
  is_active,
  is_featured,
  meta_title,
  meta_desc,
  supplier_product_url
) values (
  'sillon-de-oficina-mainz-alto-giratorio-similpiel-gris',
  'Sillón de oficina MAINZ, alto · giratorio · similpiel gris',
  'Sillón de oficina moderno. Regulación de altura mediante cilindro neumático. Mecanismo de reclinación. Base cromada con ruedas blandas. Tapizado en similpiel de color gris. Otros colores disponibles.

Dimensiones (cm): ancho 65, fondo 58, alto 110–120. Embalaje: plástico y cartón. Unidad: 1 · volumen: 0,16 m³. Producto nuevo con certificado (test report) emitido por laboratorio internacional homologado, con detalle del cumplimiento de la norma UNE o su equivalente internacional.',
  272.25,
  132.00,
  array[
    '/imagenes/productos/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris-1.jpg',
    '/imagenes/productos/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris-2.jpg',
    '/imagenes/productos/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris-3.jpg',
    '/imagenes/productos/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris-4.jpg',
    '/imagenes/productos/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris-5.jpg',
    '/imagenes/productos/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris-6.jpg'
  ]::text[],
  'sillas',
  'Sillas de oficina',
  array['oficina','sillón','Mainz','similpiel','gris','dirección','giratorio','pvp_ref']::text[],
  'INM-SMAINASGR',
  '762.SMAINASGR',
  'gruposdm',
  38,
  '{"width": 65, "height": 120, "depth": 58}'::jsonb,
  'Similpiel, acero cromado',
  'Gris',
  true,
  false,
  'Sillón de oficina MAINZ alto similpiel gris | INMOALIA',
  'Sillón MAINZ alto giratorio en similpiel gris. Base cromada, reclinación y 65×58×110–120 cm. IVA incluido.',
  'https://gruposdm.com/es/oficinas/sillas-de-oficinas/sillones-de-direccion/sillon-de-oficina-mainz-alto-giratorio-similpiel-gris.html'
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  cost_price = excluded.cost_price,
  images = excluded.images,
  category = excluded.category,
  subcategory = excluded.subcategory,
  tags = excluded.tags,
  sku = excluded.sku,
  supplier_sku = excluded.supplier_sku,
  supplier = excluded.supplier,
  stock = excluded.stock,
  dimensions = excluded.dimensions,
  material = excluded.material,
  color = excluded.color,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  meta_title = excluded.meta_title,
  meta_desc = excluded.meta_desc,
  supplier_product_url = coalesce(products.supplier_product_url, excluded.supplier_product_url),
  updated_at = now();
